### ISSUE TITLE
有对 对象的容错吗？

### ISSUE THREAD

**Issue by dazhiyu** [1004145468/IKGson#1]
如果是对象接的，返回空字符串或者数组之类的，还是会解析异常

**Comment by 1004145468** [comment]
没有对对象进行容错，只针对基本类型，如果对象都出错了，认为业务上面存在缺陷，暂时没有做这方面的容错处理。

**Comment by Alex-Cin** [comment]
不知道，我写的这个，合适你的场景吗？
https://github.com/Alex-Cin/belle
